# Generated by Django 5.1.1 on 2025-05-14 07:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('bind_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Bind Address')),
                ('protocol', models.CharField(blank=True, choices=[('TCP', 'Tcp'), ('UDP', 'Udp')], max_length=50, null=True, verbose_name='Protocol')),
                ('sidecar_deployed', models.BooleanField(default=False, verbose_name='Sidecar Deployed')),
                ('container_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Container Image')),
                ('cpu_requests', models.CharField(blank=True, max_length=50, null=True)),
                ('memory_requests', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_limits', models.CharField(blank=True, max_length=50, null=True)),
                ('memory_limits', models.CharField(blank=True, max_length=50, null=True)),
                ('env_string', models.TextField(blank=True, null=True, verbose_name='Env String')),
                ('pull_secrets_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pull Secrets Name')),
                ('pull_policy', models.CharField(blank=True, choices=[('Always', 'Always'), ('IfNotPresent', 'If Not Present'), ('Never', 'Never')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Instance Service',
            },
        ),
        migrations.RemoveField(
            model_name='flavour',
            name='protocols',
        ),
        migrations.CreateModel(
            name='HistoricalInstanceService',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('port', models.IntegerField(verbose_name='Port')),
                ('bind_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Bind Address')),
                ('protocol', models.CharField(blank=True, choices=[('TCP', 'Tcp'), ('UDP', 'Udp')], max_length=50, null=True, verbose_name='Protocol')),
                ('sidecar_deployed', models.BooleanField(default=False, verbose_name='Sidecar Deployed')),
                ('container_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Container Image')),
                ('cpu_requests', models.CharField(blank=True, max_length=50, null=True)),
                ('memory_requests', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_limits', models.CharField(blank=True, max_length=50, null=True)),
                ('memory_limits', models.CharField(blank=True, max_length=50, null=True)),
                ('env_string', models.TextField(blank=True, null=True, verbose_name='Env String')),
                ('pull_secrets_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pull Secrets Name')),
                ('pull_policy', models.CharField(blank=True, choices=[('Always', 'Always'), ('IfNotPresent', 'If Not Present'), ('Never', 'Never')], max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Instance Service',
                'verbose_name_plural': 'historical Instance Services',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='flavour',
            name='instance_services',
            field=models.ManyToManyField(blank=True, to='cloud_provider.instanceservice', verbose_name='Instance Services'),
        ),
        migrations.DeleteModel(
            name='HistoricalProtocol',
        ),
        migrations.DeleteModel(
            name='Protocol',
        ),
    ]
