# Generated by Django 5.1.1 on 2025-05-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0002_instanceservice_remove_flavour_protocols_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstanceservice',
            name='mount_pvc_storage',
            field=models.BooleanField(default=False, verbose_name='Mount PVC Storage'),
        ),
        migrations.AddField(
            model_name='instanceservice',
            name='mount_pvc_storage',
            field=models.BooleanField(default=False, verbose_name='Mount PVC Storage'),
        ),
        migrations.AlterField(
            model_name='historicalinstanceservice',
            name='bind_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='Bind Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalinstanceservice',
            name='protocol',
            field=models.CharField(choices=[('TCP', 'Tcp'), ('UDP', 'Udp')], default='TCP', max_length=50, verbose_name='Protocol'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instanceservice',
            name='bind_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='Bind Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instanceservice',
            name='protocol',
            field=models.CharField(choices=[('TCP', 'Tcp'), ('UDP', 'Udp')], default='TCP?', max_length=50, verbose_name='Protocol'),
            preserve_default=False,
        ),
    ]
