# Generated by Django 5.1.1 on 2025-05-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0002_proposalaccount_historicalproposalaccount'),
        ('cloud_provider', '0003_historicalinstanceservice_mount_pvc_storage_and_more'),
    ]

    operations = [
    ]
