# Generated by Django 5.1.1 on 2025-05-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0004_merge_20250514_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposalaccount',
            name='username',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='proposalaccount',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Username'),
        ),
    ]
