# Generated by Django 5.1.1 on 2025-05-19 15:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

INITIAL_DATA = [
]


def load_initial_data(apps, schema_editor):
    StorageConfig = apps.get_model('cloud_provider', 'StorageConfig')
    for instrument, read_only, server, server_path, enabled in INITIAL_DATA:
        StorageConfig.objects.create(
            instrument=instrument,
            read_only=read_only,
            server=server,
            server_path=server_path,
            enabled=enabled
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0006_historicalhomedirectory_homedirectory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=50, verbose_name='Instrument')),
                ('read_only', models.BooleanField(default=True, verbose_name='Read Only')),
                ('server', models.CharField(max_length=50, verbose_name='Server')),
                ('server_path', models.CharField(max_length=50, verbose_name='Server Path')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Storage Config',
            },
        ),
        migrations.CreateModel(
            name='HistoricalStorageConfig',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('instrument', models.CharField(max_length=50, verbose_name='Instrument')),
                ('read_only', models.BooleanField(default=True, verbose_name='Read Only')),
                ('server', models.CharField(max_length=50, verbose_name='Server')),
                ('server_path', models.CharField(max_length=50, verbose_name='Server Path')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Storage Config',
                'verbose_name_plural': 'historical Storage Configs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(load_initial_data, migrations.RunPython.noop),
    ]
