# Generated by Django 5.1.1 on 2025-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0007_storageconfig_historicalstorageconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalimage',
            name='home_template_path',
            field=models.CharField(max_length=255, null=True, verbose_name='Home template path'),
        ),
        migrations.AddField(
            model_name='historicalimage',
            name='user_shell',
            field=models.CharField(max_length=255, null=True, verbose_name='User shell'),
        ),
        migrations.AddField(
            model_name='image',
            name='home_template_path',
            field=models.CharField(max_length=255, null=True, verbose_name='Home template path'),
        ),
        migrations.AddField(
            model_name='image',
            name='user_shell',
            field=models.CharField(max_length=255, null=True, verbose_name='User shell'),
        ),
    ]
