# Generated by Django 5.1.1 on 2025-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0008_historicalimage_home_template_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='associated_proposals',
            field=models.ManyToManyField(blank=True, to='cloud_provider.proposalaccount', verbose_name='Associated proposals'),
        ),
    ]
