# Generated by Django 5.1.1 on 2025-05-22 13:58

from django.db import migrations, models

INITIAL_DATA = [
]


def load_initial_data(apps, schema_editor):
    StorageConfig = apps.get_model('cloud_provider', 'StorageConfig')

    StorageConfig.objects.all().delete()

    for instrument, read_only, server, server_path, enabled, home_dir_prefix in INITIAL_DATA:
        StorageConfig.objects.create(
            instrument=instrument,
            read_only=read_only,
            server=server,
            server_path=server_path,
            enabled=enabled,
            home_directory_prefix=home_dir_prefix
        )


class Migration(migrations.Migration):
    dependencies = [
        ('cloud_provider', '0009_instance_associated_proposals'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstorageconfig',
            name='home_directory_prefix',
            field=models.CharField(default='12', max_length=50, verbose_name='Home Directory Prefix'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storageconfig',
            name='home_directory_prefix',
            field=models.CharField(default='12', max_length=50, verbose_name='Home Directory Prefix'),
            preserve_default=False,
        ),
        migrations.RunPython(load_initial_data, migrations.RunPython.noop),
    ]
