# Generated by Django 5.1.1 on 2025-05-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0010_historicalstorageconfig_home_directory_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstorageconfig',
            name='extra_nfs_gids',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Extra NFS GIDs'),
        ),
        migrations.AddField(
            model_name='storageconfig',
            name='extra_nfs_gids',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Extra NFS GIDs'),
        ),
    ]
