# Generated by Django 5.1.1 on 2025-05-23 09:52

from django.db import migrations

INITIAL_DATA = [
]


def load_initial_data(apps, schema_editor):
    StorageConfig = apps.get_model('cloud_provider', 'StorageConfig')

    StorageConfig.objects.all().delete()

    for instrument, read_only, server, server_path, enabled, home_dir_prefix, extra_gids in INITIAL_DATA:
        StorageConfig.objects.create(
            instrument=instrument,
            read_only=read_only,
            server=server,
            server_path=server_path,
            enabled=enabled,
            home_directory_prefix=home_dir_prefix,
            extra_nfs_gids=extra_gids
        )

class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0011_historicalstorageconfig_extra_nfs_gids_and_more'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, migrations.RunPython.noop),
    ]
