# Generated by Django 5.1.1 on 2025-09-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0012_auto_20250523_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstanceservice',
            name='args',
            field=models.TextField(blank=True, null=True, verbose_name='Args'),
        ),
        migrations.AddField(
            model_name='historicalinstanceservice',
            name='command',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Command'),
        ),
        migrations.AddField(
            model_name='instanceservice',
            name='args',
            field=models.TextField(blank=True, null=True, verbose_name='Args'),
        ),
        migrations.AddField(
            model_name='instanceservice',
            name='command',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Command'),
        ),
        migrations.AlterField(
            model_name='historicalinstanceservice',
            name='cpu_limits',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU Limits'),
        ),
        migrations.AlterField(
            model_name='historicalinstanceservice',
            name='cpu_requests',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU Requests'),
        ),
        migrations.AlterField(
            model_name='historicalinstanceservice',
            name='memory_limits',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Memory Limits'),
        ),
        migrations.AlterField(
            model_name='historicalinstanceservice',
            name='memory_requests',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Memory Requests'),
        ),
        migrations.AlterField(
            model_name='instanceservice',
            name='cpu_limits',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU Limits'),
        ),
        migrations.AlterField(
            model_name='instanceservice',
            name='cpu_requests',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CPU Requests'),
        ),
        migrations.AlterField(
            model_name='instanceservice',
            name='memory_limits',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Memory Limits'),
        ),
        migrations.AlterField(
            model_name='instanceservice',
            name='memory_requests',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Memory Requests'),
        ),
    ]
