# Generated by Django 5.1.1 on 2025-09-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0013_historicalinstanceservice_args_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkubernetesversion',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='KubernetesVersion',
        ),
        migrations.DeleteModel(
            name='HistoricalKubernetesVersion',
        ),
    ]
