# Generated by Django 5.1.1 on 2025-09-23 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0014_remove_historicalkubernetesversion_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='historicalflavour',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='historicalimage',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='historicalimage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='image',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='image',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='flavour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cloud_provider.flavour', verbose_name='Flavour'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cloud_provider.image', verbose_name='Image'),
        ),
    ]
