# Generated by Django 5.1.1 on 2025-10-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0015_flavour_deleted_historicalflavour_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstanceservice',
            name='mount_tmp_dir',
            field=models.BooleanField(default=False, verbose_name='Mount /tmp dir'),
        ),
        migrations.AddField(
            model_name='instanceservice',
            name='mount_tmp_dir',
            field=models.BooleanField(default=False, verbose_name='Mount /tmp dir'),
        ),
    ]
