# Generated by Django 5.1.1 on 2025-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0016_historicalinstanceservice_mount_tmp_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='mount_pvc_storage',
            field=models.BooleanField(default=False, verbose_name='Mount PVC Storage'),
        ),
        migrations.AddField(
            model_name='historicalflavour',
            name='mount_pvc_storage',
            field=models.BooleanField(default=False, verbose_name='Mount PVC Storage'),
        ),
    ]
