# Generated by Django 5.1.1 on 2025-10-10 09:37

from django.db import migrations

DEFAULT_CLOUD_LIMITS = [
    ("MAX_TOTAL_RAM_ALLOWED", "Total amount of RAM allowed to use by the ACP", "47684", "MiB"),
    ("MAX_INSTANCE_AMOUNT", "Total amount of instances allowed to use by the ACP", "15", "instances"),
    ("MAX_TOTAL_CORES_ALLOWED", "Total amount of cores allowed to use by the ACP", "10", "cores"),
]


def create_default_cloud_limits(apps, schema_editor):
    for i in DEFAULT_CLOUD_LIMITS:
        apps.get_model('cloud_provider', 'CloudLimit').objects.create(name=i[0], description=i[1], value=i[2],
                                                                      unit=i[3])


class Migration(migrations.Migration):
    dependencies = [
        ('cloud_provider', '0018_cloudlimit_historicalcloudlimit'),
    ]

    operations = [
        migrations.RunPython(create_default_cloud_limits, migrations.RunPython.noop),
    ]
