# Generated by Django 5.1.1 on 2025-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0019_create_default_cloud_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavour',
            name='ram',
            field=models.FloatField(verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='historicalflavour',
            name='ram',
            field=models.FloatField(verbose_name='RAM'),
        ),
    ]
