# Generated by Django 5.1.1 on 2025-10-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0020_alter_flavour_ram_alter_historicalflavour_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstance',
            name='visa_uid',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='VISA UID'),
        ),
        migrations.AddField(
            model_name='instance',
            name='visa_uid',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='VISA UID'),
        ),
    ]
