# Generated by Django 5.1.1 on 2025-11-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0021_historicalinstance_visa_uid_instance_visa_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstorageconfig',
            name='scratch_enabled',
            field=models.BooleanField(default=False, verbose_name='Scratch Enabled'),
        ),
        migrations.AddField(
            model_name='historicalstorageconfig',
            name='scratch_server',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Scratch Server'),
        ),
        migrations.AddField(
            model_name='historicalstorageconfig',
            name='scratch_server_path',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Scratch Server Path'),
        ),
        migrations.AddField(
            model_name='storageconfig',
            name='scratch_enabled',
            field=models.BooleanField(default=False, verbose_name='Scratch Enabled'),
        ),
        migrations.AddField(
            model_name='storageconfig',
            name='scratch_server',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Scratch Server'),
        ),
        migrations.AddField(
            model_name='storageconfig',
            name='scratch_server_path',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Scratch Server Path'),
        ),
    ]
