# Generated by Django 5.1.1 on 2025-11-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0022_historicalstorageconfig_scratch_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstorageconfig',
            name='scratch_mount_path',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Scratch Mount Path'),
        ),
        migrations.AddField(
            model_name='storageconfig',
            name='scratch_mount_path',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Scratch Mount Path'),
        ),
    ]
