# Generated by Django 5.1.1 on 2025-11-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0023_historicalstorageconfig_scratch_mount_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstorageconfig',
            name='scratch_read_only',
            field=models.BooleanField(default=True, verbose_name='Scratch Read Only'),
        ),
        migrations.AddField(
            model_name='storageconfig',
            name='scratch_read_only',
            field=models.BooleanField(default=True, verbose_name='Scratch Read Only'),
        ),
    ]
