# Generated by Django 5.1.1 on 2025-11-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_provider', '0024_historicalstorageconfig_scratch_read_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstanceservice',
            name='mount_scratch_dir',
            field=models.BooleanField(default=False, verbose_name='Mount Scratch Dir'),
        ),
        migrations.AddField(
            model_name='instanceservice',
            name='mount_scratch_dir',
            field=models.BooleanField(default=False, verbose_name='Mount Scratch Dir'),
        ),
    ]
