FROM python:3.12.6-slim-bookworm
# NOTE: ARG instruction only is valid for build instructions (not ENTRYPOINT or CMD)
ARG SETTINGS_FILE

ENV PYTHONBUFFERED 1
WORKDIR /django/app

# Build deps - remove after use
RUN apt-get update && apt-get install -y \
    pkg-config \
    libmariadbclient-dev-compat \
    make \
    curl \
    gcc \
    musl-dev \
    libffi-dev \
    build-essential \
    libldap2-dev \
    libsasl2-dev \
    libssl-dev \
    bash

SHELL ["/bin/bash", "-c"]

# Set minimum TLS version to 1.0 so that it is insecure and connection with Alba SMTP server can be established
RUN sed -i 's/TLSv1.2/TLSv1.0/g' /etc/ssl/openssl.cnf

COPY requirements.txt /django/app/requirements.txt

RUN curl -LsSf https://astral.sh/uv/install.sh | env UV_INSTALL_DIR="/usr/local" sh
RUN source /usr/local/env

COPY requirements.txt /django/app/requirements.txt

#RUN uv pip install -r requirements.txt --system  --python-preference only-system
#RUN uv pip install uwsgi --system --python-preference only-system

RUN pip install -r requirements.txt
RUN pip install uwsgi

# Clean build deps
RUN apt-get -y --allow-remove-essential remove make gcc musl-dev libffi-dev && rm -rf ~/.cache/pip


COPY . /django/app

# Logs and DB conf
RUN mkdir /django/logs && mkdir -p /django/config/database
COPY ./docker_db.cnf /django/config/database/my.cnf
RUN chown 300 /django/config/database/my.cnf

# Email conf
COPY ./email.json /django/config/email.json

# SSO conf
COPY ./sso.json /django/config/sso.json

RUN groupadd django
RUN useradd -m django -g django

USER django
