[uwsgi]
chdir=/django/app/
module=settings.wsgi:application
env=DJANGO_SETTINGS_MODULE=settings.settings_prod
pidfile=/tmp/project-master.pid
http-socket=:3099
harakiri=120
max-requests=5000
static-map=/static/=static
buffer-size=32768
workers=10
http-timeout=10
cheaper-step=1
cheaper-algo=backlog
stats=127.0.0.1
lazy=True
lazy-apps=True
static-map=/static/=static
touch-reload = /django/app/README.md