"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import json
import logging
import os
import sys
from pathlib import Path

from django.urls import reverse

logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '<<USE_YOUR_OWN>>'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms'
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_api_key',
    'simple_history',
    'corsheaders',
    #'elasticapm.contrib.django',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.openid_connect',
]

LOCAL_APPS = [
    'mis_template',
    'cloud_provider',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'settings.urls'

STATIC_URL = '/static/'
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
SESSION_COOKIE_NAME = 'acp_sessionid'

CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = (
    ''
)

WSGI_APPLICATION = 'settings.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'STORAGE_ENGINE': 'INNODB',
        'OPTIONS': {
            'read_default_file': os.path.join(BASE_DIR, '..', 'config', 'database', 'my.cnf'),
        },
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'CET'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Test fixtures
TESTING_MODE = False
FIXTURE_DIRS = {
    os.path.join(BASE_DIR, 'cloud_provider', 'tests', 'fixtures'),
    os.path.join(BASE_DIR, 'mis_template', 'tests', 'fixtures'),
}

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"}, 'simple': {'format': '%(levelname)s %(message)s'},
    },
    'handlers': {
        # 'elasticapm': {
        #   'level': 'WARNING',
        #   'class': 'elasticapm.contrib.django.handlers.LoggingHandler',
        # },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'null': {
            'level': 'DEBUG', 'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'], 'level': 'ERROR', 'propagate': False,
        },
        'settings': {
            'handlers': ['console'], 'level': 'DEBUG', 'propagate': False,
        },
        'mis_template': {
            'handlers': ['console'], 'level': 'DEBUG', 'propagate': False,
        },
        'cloud_provider': {
            'handlers': ['console'], 'level': 'DEBUG', 'propagate': False,
        },
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

"""
# COMMENTED OUT -- CURRENTLY NO ELASTIC-APM PYTHON AGENT SUPPORT FOR ASGI
try:
    with open(os.path.join(BASE_DIR, '..', 'config', 'apm.cnf')) as apm_conf_file:
        ELASTIC_APM = json.load(apm_conf_file)
except Exception as e:
    logger.error(e)
    ELASTIC_APM = {'SERVICE_NAME': 'shift-management-tool', 'SERVER_URL': '', 'DEBUG': True, 'DISABLE_SEND': True,
                   'CENTRAL_CONFIG': False}
"""
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]

DEFAULT_PAGINATION_OBJECTS = 20

REST_FRAMEWORK = {
    'UNICODE_JSON': False,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework_api_key.permissions.HasAPIKey',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'TEST_REQUEST_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'EXCEPTION_HANDLER': 'mis_template.utils.exception.custom_exception_handler'
}

# API KEY SETTINGS
API_KEY_CUSTOM_HEADER = 'HTTP_X_AUTH_TOKEN'

VISA_INSTANCE_NAME_PREFIX = "acp-"

# PUBLIC KEY SETTINGS
VISA_PUBLIC_KEY_NAME = 'pam-key'
VISA_PUBLIC_KEY_FILENAME = 'public.key'
VISA_PUBLIC_KEY_MOUNT_PATH = '/etc/visa/'

VISA_INSTANCE_SUDOERS_SECURITY_GROUPS = "INSTANCE_SUDOERS"
VISA_INSTANCE_DEFAULT_TIMEZONE = 'Europe/Madrid'

VISA_INSTANCE_PERSISTENCE_ACCESS_MODE = 'ReadWriteMany'
VISA_INSTANCE_PERSISTENCE_STORAGE_CLASS = 'affnas-csi'
VISA_INSTANCE_PERSISTENCE_MOUNT_PATH = '/persistence'
VISA_STORAGE_MOUNT_PREFIX = '/investigation-data'

VISA_CLOUD_PROVIDER_USE_STATEFULSET = True

EMAIL_HOST = '<<USE_YOUR_OWN>>'
EMAIL_USE_TLS = True
EMAIL_PORT = 25
try:
    with open(os.path.join(BASE_DIR, '..', 'config', 'email.json')) as email_conf_file:
        email_credentials = json.load(email_conf_file)
        EMAIL_HOST_USER = email_credentials['user']
        EMAIL_HOST_PASSWORD = email_credentials['password']
except Exception as e:
    logger.error(e)

EMAIL_NOTIFICATIONS = True

FORCE_SCRIPT_NAME = '/'

# SSO stuff
JWT_DEFAULT_ALGORITHMS_LIST = ['HS512']
JWT_DEFAULT_OPTS = {'verify_signature': False}
SESSION_ENGINE = 'mis_template.sso_authentication.session_store'
CUSTOM_SESSION_ENGINE_SSO_PROVIDER_NAME = 'alba-sso'
LOGIN_URL = "/alba-sso/login/"
LOGIN_REDIRECT_URL = '/'
SESSION_COOKIE_AGE = 60 * 60 * 3  # 3 hours
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
ACCOUNT_ADAPTER = 'mis_template.sso_authentication.adapters.ALBASSOAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'mis_template.sso_authentication.adapters.ALBASSOSocialAccountAdapter'
SSO_PROVIDER_NAME = 'alba-sso'
SOCIALACCOUNT_PROVIDERS = {
    "openid_connect": {
        "VERIFIED_EMAIL": True,
        "APPS": [
        ],
    }
}

if not os.getenv("OIDC_AUTH_DISABLE") == "1":
    try:
        data = open(os.path.join(BASE_DIR, '..', 'config', 'sso.json')).read()
        sso_config = json.loads(data)
        SOCIALACCOUNT_PROVIDERS['openid_connect']['APPS'].append(sso_config)
        SSO_LOGOUT_REDIRECT_URL = f"{sso_config['settings']['server_url']}/protocol/openid-connect/logout?client_id={sso_config['client_id']}&post_logout_redirect_uri={{}}"
    except IOError as e:
        logger.error("SSO configuration file not found")

# LDAP settings
LDAP_URL = os.getenv('LDAP_URL', '')
LDAP_BASE_DN = os.getenv('LDAP_BASE_DN', '')
