
# Printer configuration file for CUPS v2.4
<Printer VISA>
Info VISA Printer
Location
MakeModel Custom VISA Model
DeviceURI visa:/queue
State Idle
StateTime 0
Accepting Yes
Shared Yes
JobSheets none none
QuotaPeriod 0
PageLimit 0
KLimit 0
OpPolicy default
ErrorPolicy stop-printer
</Printer>